import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { connection } from "next/server";
import "./globals.css";
import Providers from "./providers";
import SiteFooter from "./components/SiteFooter";
import { getClerkPublishableKey } from "@/lib/clerkConfigured";

export const metadata: Metadata = {
  title: "Surrenderless Form Assistant",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const publishableKey = getClerkPublishableKey();

  if (!publishableKey) {
    await connection();
  }

  const body = (
    <html lang="en">
      <body className="antialiased">
        <Providers>
          {children}
          <SiteFooter />
        </Providers>
      </body>
    </html>
  );

  if (!publishableKey) {
    return body;
  }

  return <ClerkProvider publishableKey={publishableKey}>{body}</ClerkProvider>;
}
